/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droider_debugjniso_TestJniMethods */

#ifndef _Included_com_droider_debugjniso_TestJniMethods
#define _Included_com_droider_debugjniso_TestJniMethods
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_droider_debugjniso_TestJniMethods_jniString(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
