/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droider_jnimethods_TestJniMethods */

#ifndef _Included_com_droider_jnimethods_TestJniMethods
#define _Included_com_droider_jnimethods_TestJniMethods
#ifdef __cplusplus
extern "C" {
#endif

/* 请在jnimethods.c上点右键，在属性中将文件编码改为utf-8 */
JNIEXPORT void JNICALL Java_com_droider_jnimethods_TestJniMethods_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
